# Imperial Geass Noir for kitty

background #07070B
foreground #E8E1D2
cursor #C4A45A
cursor_text_color #07070B

selection_background #241D36
selection_foreground #E8E1D2

url_color #C4A45A
active_border_color #07070B
inactive_border_color #07070B
bell_border_color #111018
visual_bell_color #191522

color0 #0B0911
color1 #B04A5A
color2 #7A946F
color3 #C4A45A
color4 #6D57B1
color5 #8F6BC4
color6 #7FA6A5
color7 #D8D0C0

color8 #2B2238
color9 #C96674
color10 #91AA82
color11 #D6BB72
color12 #856FDA
color13 #AA84D6
color14 #95BDBB
color15 #F0E8DA
